app = "quickvibe-rt-srikrishna"
primary_region = "sin"

[build]
  dockerfile = "apps/rt/Dockerfile"

[http_service]
  internal_port = 2567
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[env]
  NODE_ENV = "production"
  PORT = "2567"
